[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Christopher Roberts <10robertsc@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
